# Generated by Django 4.1.7 on 2023-06-11 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_ad_category_alter_ad_title_alter_category_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.comment'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
