# Generated by Django 4.1.7 on 2023-06-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_ad_comment_alter_ad_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='file',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
